server:
  port: 9999

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://172.28.8.170:3306/assets?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: false
    # 自动生成表结构
    generate-ddl: false
    hibernate:
      ddl-auto: none
